name: xterm
description: xterm.dart is a fast and fully-featured terminal emulator for Flutter applications, with support for mobile and desktop platforms.
version: 4.0.0
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  convert: ^3.1.2
  meta: ^1.18.0
  quiver: ^3.2.2
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  zmodem: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

