// Extracted from the former colour cascade in styles/tokens.css. The extraction
// script no longer exists; these values are now hand-maintained.
// Palette overrides live in ./dracula.ts.

export const draculaDarkTokens = {
	accent: "#3e4052",
	accentForeground: "#f1f0eb",
	accentWeak: "var(--color-accent-weak)",
	amber: "var(--color-warning)",
	background: "#282a36",
	bg: "var(--color-bg-primary)",
	bg0: "var(--color-bg-primary)",
	bg1: "var(--color-bg-secondary)",
	bg2: "var(--color-bg-tertiary)",
	border: "oklch(1 0 0 / 10%)",
	border1: "var(--color-border-strong)",
	bridgeAccent: "var(--color-accent)",
	bridgeAccentDim: "var(--color-accent-dim)",
	bridgeAccentFg: "var(--color-accent-foreground)",
	bridgeAccentStrong: "var(--color-accent-strong)",
	bridgeAccentWeak: "var(--color-accent-weak)",
	bridgeBorder: "var(--color-border)",
	bridgeBorderStrong: "var(--color-border-strong)",
	bridgeDanger: "var(--color-danger)",
	bridgeDangerStrong: "var(--color-danger-strong)",
	bridgeInteractiveActive: "var(--color-interactive-active)",
	bridgeInteractiveHover: "var(--color-interactive-hover)",
	bridgePreviewBody: "var(--color-preview-body)",
	bridgePreviewCard: "var(--color-preview-card-border)",
	bridgePreviewHeading: "var(--color-preview-heading)",
	bridgePreviewLink: "var(--color-preview-link)",
	bridgePreviewMuted: "var(--color-preview-muted)",
	bridgePreviewSuccess: "var(--color-preview-success-bg)",
	bridgePreviewTerminal: "var(--color-preview-terminal-bg)",
	bridgePreviewTerminalBorder: "var(--color-preview-terminal-border)",
	bridgePreviewTerminalFg: "var(--color-preview-terminal-fg)",
	bridgePreviewTile: "var(--color-preview-tile-bg)",
	bridgePreviewTileBorder: "var(--color-preview-tile-border)",
	bridgeScrim: "var(--color-scrim)",
	bridgeStatusExited: "var(--color-status-exited)",
	bridgeStatusIdle: "var(--color-status-idle)",
	bridgeStatusInReview: "var(--color-status-in-review)",
	bridgeStatusMerged: "var(--color-status-merged)",
	bridgeStatusNeedsYou: "var(--color-status-needs-you)",
	bridgeStatusReady: "var(--color-status-ready)",
	bridgeStatusTerminated: "var(--color-status-terminated)",
	bridgeStatusTerminatedForeground: "var(--color-status-terminated-foreground)",
	bridgeStatusUnknown: "var(--color-status-unknown)",
	bridgeStatusWorking: "var(--color-status-working)",
	bridgeSuccess: "var(--color-success)",
	bridgeWarning: "var(--color-warning)",
	bridgeWorking: "var(--color-working)",
	card: "#353748",
	cardForeground: "#f1f0eb",
	chart1: "oklch(0.871 0.006 286.286)",
	chart2: "oklch(0.552 0.016 285.938)",
	chart3: "oklch(0.442 0.017 285.786)",
	chart4: "oklch(0.37 0.013 285.805)",
	chart5: "oklch(0.274 0.006 286.033)",
	colorAccentDim: "var(--chart-4)",
	colorAccentStrong: "var(--primary)",
	colorAccentWeak: "color-mix(in oklch, var(--primary) 16%, transparent)",
	bgAgentsSheet: "var(--color-bg-settings-dialog)",
	bgAgentsSheetControl: "var(--input)",
	bgCommandItemActive: "color-mix(in oklch, var(--popover) 88%, var(--foreground) 12%)",
	bgCommandPalette: "var(--popover)",
	bgComposerChip: "color-mix(in oklab, var(--input) 55%, transparent)",
	bgComposerChipHover: "var(--secondary)",
	bgImportCard: "var(--popover)",
	bgImportCardHover: "var(--accent)",
	bgImportChip: "var(--secondary)",
	bgImportIllustration: "var(--color-bg-import-chip)",
	bgImportModal: "var(--card)",
	bgSettingsDialog: "var(--card)",
	bgSettingsInput: "var(--input)",
	bgSettingsMenu: "var(--popover)",
	bgSettingsMenuSelected: "color-mix(in oklch, var(--popover) 92%, var(--foreground) 8%)",
	bgSettingsRow: "transparent",
	bgTerminal: "#101317e7",
	bgTerminalOpaque: "#101317",
	bgTopbar: "var(--background)",
	bgTopbarRaised: "var(--secondary)",
	borderAgentsSheet: "var(--border)",
	borderCommandPalette: "var(--border)",
	borderImportModal: "var(--border)",
	borderSettings: "var(--color-border-welcome-panel)",
	borderSettingsDialog: "oklch(1 0 0 / 3%)",
	borderSettingsDialogHeader: "oklch(1 0 0 / 3%)",
	borderSettingsInput: "var(--color-border-settings-dialog)",
	borderSettingsMenu: "color-mix(in oklch, var(--border) 60%, var(--foreground) 40%)",
	borderTopbar: "var(--border)",
	borderTopbarStrong: "var(--input)",
	borderWelcomePanel: "var(--border)",
	brandLogo: "#79b0dc",
	brandLogoBright: "#a5cde7",
	brandLogoForeground: "#0a0b0d",
	colorInteractiveActive: "color-mix(in oklch, var(--foreground) 7%, transparent)",
	colorInteractiveHover: "color-mix(in oklch, var(--foreground) 4%, transparent)",
	overlayFaint: "color-mix(in oklch, var(--foreground) 2%, transparent)",
	overlaySubtle: "color-mix(in oklch, var(--foreground) 1.8%, transparent)",
	previewBg: "#f7f8fb",
	previewBody: "#526070",
	previewCardBorder: "#d7dee8",
	previewFg: "#17202a",
	previewHeading: "#111827",
	previewLink: "#2f5b9d",
	previewMuted: "#687384",
	previewSuccessBg: "#e7f8ed",
	previewTerminalBg: "#0f172a",
	previewTerminalBorder: "#dce4ef",
	previewTerminalFg: "#cbd5e1",
	previewTileBg: "#fbfcfe",
	previewTileBorder: "#e1e7ef",
	projectAccentMint: "var(--chart-1)",
	projectAccentSky: "var(--chart-2)",
	projectAccentViolet: "#c4b5fd",
	purple: "var(--chart-4)",
	scrim: "color-mix(in oklch, var(--background) 85%, transparent)",
	scrollbar: "color-mix(in oklch, var(--foreground) 12%, transparent)",
	scrollbarBoard: "color-mix(in oklch, var(--foreground) 26%, transparent)",
	scrollbarBoardHover: "color-mix(in oklch, var(--foreground) 45%, transparent)",
	settingsAccent: "var(--primary)",
	settingsFooterButtonPrimaryFg: "var(--primary-foreground)",
	settingsSwitchOn: "var(--primary)",
	statusInReview: "#facc15",
	statusMerged: "var(--color-status-ready)",
	statusNeedsYou: "#fb923c",
	statusReady: "#4ade80",
	statusTerminatedForeground: "var(--chart-3)",
	statusUnknown: "var(--chart-4)",
	statusWorking: "#60a5fa",
	successBright: "var(--chart-1)",
	termBlack: "#1f2329",
	termBlue: "#5b9cff",
	termBrightBlack: "#7f8792",
	termBrightBlue: "#79b1ff",
	termBrightCyan: "#79d4df",
	termBrightGreen: "#62df91",
	termBrightMagenta: "#d99aee",
	termBrightRed: "#ff7b7c",
	termBrightWhite: "#f4f5f7",
	termBrightYellow: "#f2d66d",
	termCyan: "#56b6c2",
	termGreen: "#44c97a",
	termMagenta: "#c678dd",
	termRed: "#f05d5e",
	termSelectionDark: "rgb(77 141 255 / 0.3)",
	termSelectionInactive: "rgb(128 128 128 / 0.2)",
	termSelectionInactiveLight: "rgb(128 128 128 / 0.15)",
	termSelectionLight: "rgb(37 99 235 / 0.25)",
	termWhite: "#d7dae0",
	termYellow: "#e5c34b",
	textAgentsSheetDescription: "var(--muted-foreground)",
	textAgentsSheetLabel: "var(--foreground)",
	textAgentsSheetTitle: "var(--foreground)",
	textCommandItem: "var(--foreground)",
	textCommandMuted: "var(--muted-foreground)",
	textCommandPlaceholder: "var(--muted-foreground)",
	textImportMuted: "var(--muted-foreground)",
	textImportSep: "var(--color-text-import-muted)",
	textImportTitle: "var(--foreground)",
	textMarkdownCode: "var(--color-brand-logo)",
	textMarkdownLink: "var(--color-brand-logo)",
	textMarkdownLinkHover: "var(--color-brand-logo-bright)",
	textSettingsInput: "var(--foreground)",
	textSettingsMuted: "var(--muted-foreground)",
	textSettingsPlaceholder: "var(--muted-foreground)",
	textSettingsRow: "var(--foreground)",
	textSettingsTitle: "var(--foreground)",
	textTerminal: "#d7d7d2",
	textTerminalDim: "#7c7c7c",
	textTopbar: "var(--foreground)",
	textTopbarMuted: "var(--muted-foreground)",
	textTopbarPassive: "var(--chart-3)",
	working: "var(--color-status-working)",
	destructive: "oklch(0.704 0.191 22.216)",
	elevationLg: "0 8px 40px color-mix(in oklch, var(--background) 55%, transparent)",
	elevationSm: "0 1px 0 color-mix(in oklch, var(--background) 35%, transparent)",
	fg: "var(--color-text-primary)",
	fgMuted: "var(--color-text-muted)",
	fgPassive: "var(--color-text-passive)",
	foreground: "#f1f0eb",
	green: "var(--color-success)",
	input: "oklch(1 0 0 / 6%)",
	interactiveActive: "var(--color-interactive-active)",
	interactiveHover: "var(--color-interactive-hover)",
	muted: "#3e4052",
	mutedForeground: "#9ba3b6",
	orange: "var(--color-working)",
	popover: "#3f4253",
	popoverForeground: "#f1f0eb",
	primary: "#bd93f9",
	primaryForeground: "#282a36",
	red: "var(--color-danger)",
	ring: "#bd93f9",
	ringWidthFocus: "3px",
	secondary: "#3e4052",
	secondaryForeground: "#f1f0eb",
	shadowCommandPalette: "var(--elevation-xl)",
	shadowImportModal: "0 0 0 1px var(--border), var(--elevation-md)",
	shadowPopover: "var(--elevation-xl)",
	shadowSettingsDialog: "var(--elevation-xl)",
	shadowSettingsQr: "var(--elevation-md)",
	sidebar: "#22232d",
	sidebarAccent: "#3e4052",
	sidebarAccentForeground: "#f1f0eb",
	sidebarForeground: "#f1f0eb",
	sidebarPrimary: "#bd93f9",
	sidebarPrimaryForeground: "#282a36",
	sidebarRing: "#bd93f9",
	surface: "var(--color-bg-secondary)",
	termBg: "var(--color-bg-terminal)",
} as const;

export const draculaLightTokens = {
	accent: "#f7f4e4",
	accentForeground: "#2f2e2e",
	accentWeak: "var(--color-accent-weak)",
	amber: "var(--color-warning)",
	background: "#fffbeb",
	bg: "var(--color-bg-primary)",
	bg0: "var(--color-bg-primary)",
	bg1: "var(--color-bg-secondary)",
	bg2: "var(--color-bg-tertiary)",
	border: "oklch(0 0 0 / 10%)",
	border1: "var(--color-border-strong)",
	bridgeAccent: "var(--color-accent)",
	bridgeAccentDim: "var(--color-accent-dim)",
	bridgeAccentFg: "var(--color-accent-foreground)",
	bridgeAccentStrong: "var(--color-accent-strong)",
	bridgeAccentWeak: "var(--color-accent-weak)",
	bridgeBorder: "var(--color-border)",
	bridgeBorderStrong: "var(--color-border-strong)",
	bridgeDanger: "var(--color-danger)",
	bridgeDangerStrong: "var(--color-danger-strong)",
	bridgeInteractiveActive: "var(--color-interactive-active)",
	bridgeInteractiveHover: "var(--color-interactive-hover)",
	bridgePreviewBody: "var(--color-preview-body)",
	bridgePreviewCard: "var(--color-preview-card-border)",
	bridgePreviewHeading: "var(--color-preview-heading)",
	bridgePreviewLink: "var(--color-preview-link)",
	bridgePreviewMuted: "var(--color-preview-muted)",
	bridgePreviewSuccess: "var(--color-preview-success-bg)",
	bridgePreviewTerminal: "var(--color-preview-terminal-bg)",
	bridgePreviewTerminalBorder: "var(--color-preview-terminal-border)",
	bridgePreviewTerminalFg: "var(--color-preview-terminal-fg)",
	bridgePreviewTile: "var(--color-preview-tile-bg)",
	bridgePreviewTileBorder: "var(--color-preview-tile-border)",
	bridgeScrim: "var(--color-scrim)",
	bridgeStatusExited: "var(--color-status-exited)",
	bridgeStatusIdle: "var(--color-status-idle)",
	bridgeStatusInReview: "var(--color-status-in-review)",
	bridgeStatusMerged: "var(--color-status-merged)",
	bridgeStatusNeedsYou: "var(--color-status-needs-you)",
	bridgeStatusReady: "var(--color-status-ready)",
	bridgeStatusTerminated: "var(--color-status-terminated)",
	bridgeStatusTerminatedForeground: "var(--color-status-terminated-foreground)",
	bridgeStatusUnknown: "var(--color-status-unknown)",
	bridgeStatusWorking: "var(--color-status-working)",
	bridgeSuccess: "var(--color-success)",
	bridgeWarning: "var(--color-warning)",
	bridgeWorking: "var(--color-working)",
	card: "#fcf8e8",
	cardForeground: "#2f2e2e",
	chart1: "oklch(0.871 0.006 286.286)",
	chart2: "oklch(0.552 0.016 285.938)",
	chart3: "oklch(0.442 0.017 285.786)",
	chart4: "oklch(0.37 0.013 285.805)",
	chart5: "oklch(0.274 0.006 286.033)",
	colorAccentDim: "var(--chart-1)",
	colorAccentStrong: "var(--primary)",
	colorAccentWeak: "color-mix(in oklch, var(--primary) 12%, transparent)",
	bgAgentsSheet: "var(--color-bg-settings-dialog)",
	bgAgentsSheetControl: "var(--input)",
	bgCommandItemActive: "color-mix(in oklch, var(--popover) 88%, var(--foreground) 12%)",
	bgCommandPalette: "var(--popover)",
	bgComposerChip: "color-mix(in oklab, var(--input) 55%, transparent)",
	bgComposerChipHover: "var(--secondary)",
	bgImportCard: "var(--card)",
	bgImportCardHover: "var(--accent)",
	bgImportChip: "var(--secondary)",
	bgImportIllustration: "var(--color-bg-import-chip)",
	bgImportModal: "var(--popover)",
	bgSettingsDialog: "var(--card)",
	bgSettingsInput: "var(--input)",
	bgSettingsMenu: "var(--popover)",
	bgSettingsMenuSelected: "color-mix(in oklch, var(--popover) 92%, var(--foreground) 8%)",
	bgSettingsRow: "var(--card)",
	bgTerminal: "#f5f5f4",
	bgTerminalOpaque: "#f5f5f4",
	bgTopbar: "var(--background)",
	bgTopbarRaised: "var(--secondary)",
	borderAgentsSheet: "var(--border)",
	borderCommandPalette: "var(--border)",
	borderImportModal: "var(--border)",
	borderSettings: "var(--color-border-welcome-panel)",
	borderSettingsDialog: "var(--border)",
	borderSettingsDialogHeader: "color-mix(in oklch, var(--border) 70%, transparent)",
	borderSettingsInput: "var(--color-border-settings-dialog)",
	borderSettingsMenu: "color-mix(in oklch, var(--border) 60%, var(--foreground) 40%)",
	borderTopbar: "var(--border)",
	borderTopbarStrong: "var(--input)",
	borderWelcomePanel: "var(--border)",
	brandLogo: "#304c83",
	brandLogoBright: "#466daa",
	brandLogoForeground: "#ffffff",
	colorInteractiveActive: "color-mix(in oklch, var(--foreground) 7%, transparent)",
	colorInteractiveHover: "color-mix(in oklch, var(--foreground) 4%, transparent)",
	overlayFaint: "color-mix(in oklch, var(--foreground) 3%, transparent)",
	overlaySubtle: "color-mix(in oklch, var(--foreground) 2%, transparent)",
	previewBg: "#f7f8fb",
	previewBody: "#526070",
	previewCardBorder: "#d7dee8",
	previewFg: "#17202a",
	previewHeading: "#111827",
	previewLink: "#2f5b9d",
	previewMuted: "#687384",
	previewSuccessBg: "#e7f8ed",
	previewTerminalBg: "#0f172a",
	previewTerminalBorder: "#dce4ef",
	previewTerminalFg: "#cbd5e1",
	previewTileBg: "#fbfcfe",
	previewTileBorder: "#e1e7ef",
	projectAccentMint: "var(--chart-1)",
	projectAccentSky: "var(--chart-2)",
	projectAccentViolet: "#c4b5fd",
	purple: "var(--chart-4)",
	scrim: "color-mix(in oklch, var(--foreground) 45%, transparent)",
	scrollbar: "color-mix(in oklch, var(--foreground) 12%, transparent)",
	scrollbarBoard: "color-mix(in oklch, var(--foreground) 26%, transparent)",
	scrollbarBoardHover: "color-mix(in oklch, var(--foreground) 45%, transparent)",
	settingsAccent: "var(--primary)",
	settingsFooterButtonPrimaryFg: "var(--primary-foreground)",
	settingsSwitchOn: "var(--primary)",
	statusInReview: "#ca8a04",
	statusMerged: "var(--color-status-ready)",
	statusNeedsYou: "#ea580c",
	statusReady: "#16a34a",
	statusTerminatedForeground: "var(--chart-3)",
	statusUnknown: "var(--chart-4)",
	statusWorking: "#2563eb",
	successBright: "var(--chart-1)",
	termBlack: "#24292f",
	termBlue: "#3b5aa6",
	termBrightBlack: "#4c535b",
	termBrightBlue: "#31487f",
	termBrightCyan: "#316061",
	termBrightGreen: "#265231",
	termBrightMagenta: "#5f4476",
	termBrightRed: "#7e3330",
	termBrightWhite: "#24292f",
	termBrightYellow: "#6b5108",
	termCyan: "#3d7a7a",
	termGreen: "#2e6b3e",
	termMagenta: "#7b5799",
	termRed: "#a13c37",
	termSelectionDark: "rgb(77 141 255 / 0.3)",
	termSelectionInactive: "rgb(128 128 128 / 0.2)",
	termSelectionInactiveLight: "rgb(128 128 128 / 0.15)",
	termSelectionLight: "rgb(37 99 235 / 0.25)",
	termWhite: "#666d75",
	termYellow: "#87660f",
	textAgentsSheetDescription: "var(--muted-foreground)",
	textAgentsSheetLabel: "var(--foreground)",
	textAgentsSheetTitle: "var(--foreground)",
	textCommandItem: "var(--foreground)",
	textCommandMuted: "var(--muted-foreground)",
	textCommandPlaceholder: "var(--muted-foreground)",
	textImportMuted: "var(--muted-foreground)",
	textImportSep: "var(--color-text-import-muted)",
	textImportTitle: "var(--foreground)",
	textMarkdownCode: "var(--color-brand-logo)",
	textMarkdownLink: "var(--color-brand-logo)",
	textMarkdownLinkHover: "var(--color-brand-logo-bright)",
	textSettingsInput: "var(--foreground)",
	textSettingsMuted: "var(--muted-foreground)",
	textSettingsPlaceholder: "var(--muted-foreground)",
	textSettingsRow: "var(--foreground)",
	textSettingsTitle: "var(--foreground)",
	textTerminal: "#24292f",
	textTerminalDim: "#6b7280",
	textTopbar: "var(--foreground)",
	textTopbarMuted: "var(--muted-foreground)",
	textTopbarPassive: "var(--chart-3)",
	working: "var(--color-status-working)",
	destructive: "oklch(0.577 0.245 27.325)",
	elevationLg: "0 16px 48px color-mix(in oklch, var(--foreground) 16%, transparent)",
	elevationSm: "0 1px 0 color-mix(in oklch, var(--foreground) 6%, transparent)",
	fg: "var(--color-text-primary)",
	fgMuted: "var(--color-text-muted)",
	fgPassive: "var(--color-text-passive)",
	foreground: "#2f2e2e",
	green: "var(--color-success)",
	input: "oklch(0 0 0 / 6%)",
	interactiveActive: "var(--color-interactive-active)",
	interactiveHover: "var(--color-interactive-hover)",
	muted: "#f7f4e4",
	mutedForeground: "#726d5a",
	orange: "var(--color-working)",
	popover: "#fffeee",
	popoverForeground: "#2f2e2e",
	primary: "#644ac9",
	primaryForeground: "#fffbeb",
	red: "var(--color-danger)",
	ring: "#644ac9",
	ringWidthFocus: "3px",
	secondary: "#f7f4e4",
	secondaryForeground: "#2f2e2e",
	shadowCommandPalette: "var(--elevation-xl)",
	shadowImportModal: "0 0 0 1px var(--border), var(--elevation-md)",
	shadowPopover: "var(--elevation-xl)",
	shadowSettingsDialog: "var(--elevation-xl)",
	shadowSettingsQr: "var(--elevation-md)",
	sidebar: "#fffef6",
	sidebarAccent: "#f7f4e4",
	sidebarAccentForeground: "#2f2e2e",
	sidebarForeground: "#2f2e2e",
	sidebarPrimary: "#644ac9",
	sidebarPrimaryForeground: "#fffbeb",
	sidebarRing: "#644ac9",
	surface: "var(--color-bg-secondary)",
	termBg: "var(--color-bg-terminal)",
} as const;
