// Extracted from the former colour cascade in styles/tokens.css, then
// hand-extended with the slots documented at the end of
// token-map.generated.ts. The extraction script no longer exists; these values
// are now hand-maintained.
import { defineSkin } from "../app-skin";

export const lightSkin = defineSkin({
	accent: "oklch(0.967 0.001 286.375)",
	accentForeground: "oklch(0.21 0.006 285.885)",
	accentWeak: "var(--color-accent-weak)",
	amber: "var(--color-warning)",
	background: "oklch(0.985 0 0)",
	bg: "var(--color-bg-primary)",
	bg0: "var(--color-bg-primary)",
	bg1: "var(--color-bg-secondary)",
	bg2: "var(--color-bg-tertiary)",
	blurOverlay: "1px",
	border: "oklch(0.945 0.003 286.32)",
	border1: "var(--color-border-strong)",
	bridgeAccent: "var(--color-accent)",
	bridgeAccentDim: "var(--color-accent-dim)",
	bridgeAccentFg: "var(--color-accent-foreground)",
	bridgeAccentStrong: "var(--color-accent-strong)",
	bridgeAccentWeak: "var(--color-accent-weak)",
	bridgeBorder: "var(--color-border)",
	bridgeBorderStrong: "var(--color-border-strong)",
	bridgeDanger: "var(--color-danger)",
	bridgeDangerStrong: "var(--color-danger-strong)",
	bridgeInteractiveActive: "var(--color-interactive-active)",
	bridgeInteractiveHover: "var(--color-interactive-hover)",
	bridgePreviewBody: "var(--color-preview-body)",
	bridgePreviewCard: "var(--color-preview-card-border)",
	bridgePreviewHeading: "var(--color-preview-heading)",
	bridgePreviewLink: "var(--color-preview-link)",
	bridgePreviewMuted: "var(--color-preview-muted)",
	bridgePreviewSuccess: "var(--color-preview-success-bg)",
	bridgePreviewTerminal: "var(--color-preview-terminal-bg)",
	bridgePreviewTerminalBorder: "var(--color-preview-terminal-border)",
	bridgePreviewTerminalFg: "var(--color-preview-terminal-fg)",
	bridgePreviewTile: "var(--color-preview-tile-bg)",
	bridgePreviewTileBorder: "var(--color-preview-tile-border)",
	bridgeScrim: "var(--color-scrim)",
	bridgeStatusExited: "var(--color-status-exited)",
	bridgeStatusIdle: "var(--color-status-idle)",
	bridgeStatusInReview: "var(--color-status-in-review)",
	bridgeStatusMerged: "var(--color-status-merged)",
	bridgeStatusNeedsYou: "var(--color-status-needs-you)",
	bridgeStatusReady: "var(--color-status-ready)",
	bridgeStatusTerminated: "var(--color-status-terminated)",
	bridgeStatusTerminatedForeground: "var(--color-status-terminated-foreground)",
	bridgeStatusUnknown: "var(--color-status-unknown)",
	bridgeStatusWorking: "var(--color-status-working)",
	bridgeSuccess: "var(--color-success)",
	bridgeWarning: "var(--color-warning)",
	bridgeWorking: "var(--color-working)",
	card: "oklch(0.985 0 0)",
	cardForeground: "oklch(0.141 0.005 285.823)",
	chart1: "oklch(0.871 0.006 286.286)",
	chart2: "oklch(0.552 0.016 285.938)",
	chart3: "oklch(0.442 0.017 285.786)",
	chart4: "oklch(0.37 0.013 285.805)",
	chart5: "oklch(0.274 0.006 286.033)",
	colorAccentDim: "var(--chart-1)",
	colorAccentStrong: "var(--primary)",
	colorAccentWeak: "color-mix(in oklch, var(--primary) 12%, transparent)",
	bgAgentsSheet: "var(--color-bg-settings-dialog)",
	bgAgentsSheetControl: "var(--input)",
	bgCommandItemActive: "color-mix(in oklch, var(--popover) 88%, var(--foreground) 12%)",
	bgCommandPalette: "var(--popover)",
	bgComposerChip: "color-mix(in oklab, var(--input) 55%, transparent)",
	bgComposerChipHover: "var(--secondary)",
	bgImportCard: "var(--card)",
	bgImportCardHover: "var(--accent)",
	bgImportChip: "var(--secondary)",
	bgImportIllustration: "var(--color-bg-import-chip)",
	bgImportModal: "var(--popover)",
	bgSettingsDialog: "var(--card)",
	bgSettingsInput: "var(--input)",
	bgSettingsMenu: "var(--popover)",
	bgSettingsMenuSelected: "color-mix(in oklch, var(--popover) 92%, var(--foreground) 8%)",
	bgSettingsRow: "var(--card)",
	bgTerminal: "#f5f5f4",
	bgTerminalOpaque: "#f5f5f4",
	bgTopbar: "var(--background)",
	bgTopbarRaised: "var(--secondary)",
	borderAgentsSheet: "var(--border)",
	borderCommandPalette: "var(--border)",
	borderImportModal: "var(--border)",
	borderSettings: "var(--color-border-welcome-panel)",
	borderSettingsDialog: "var(--border)",
	borderSettingsDialogHeader: "color-mix(in oklch, var(--border) 70%, transparent)",
	borderSettingsInput: "var(--color-border-settings-dialog)",
	borderSettingsMenu: "color-mix(in oklch, var(--border) 60%, var(--foreground) 40%)",
	borderTopbar: "var(--border)",
	borderTopbarStrong: "var(--input)",
	borderWelcomePanel: "var(--border)",
	brandLogo: "#304c83",
	brandLogoBright: "#466daa",
	brandLogoForeground: "#ffffff",
	colorInteractiveActive: "color-mix(in oklch, var(--foreground) 7%, transparent)",
	colorInteractiveHover: "color-mix(in oklch, var(--foreground) 4%, transparent)",
	overlayFaint: "color-mix(in oklch, var(--foreground) 3%, transparent)",
	overlaySubtle: "color-mix(in oklch, var(--foreground) 2%, transparent)",
	previewBg: "#f7f8fb",
	previewBody: "#526070",
	previewCardBorder: "#d7dee8",
	previewFg: "#17202a",
	previewHeading: "#111827",
	previewLink: "#2f5b9d",
	previewMuted: "#687384",
	previewSuccessBg: "#e7f8ed",
	previewTerminalBg: "#0f172a",
	previewTerminalBorder: "#dce4ef",
	previewTerminalFg: "#cbd5e1",
	previewTileBg: "#fbfcfe",
	previewTileBorder: "#e1e7ef",
	projectAccentMint: "var(--chart-1)",
	projectAccentSky: "var(--chart-2)",
	projectAccentViolet: "#c4b5fd",
	purple: "var(--chart-4)",
	scrim: "color-mix(in oklch, var(--foreground) 45%, transparent)",
	scrollbar: "color-mix(in oklch, var(--foreground) 12%, transparent)",
	scrollbarBoard: "color-mix(in oklch, var(--foreground) 26%, transparent)",
	scrollbarBoardHover: "color-mix(in oklch, var(--foreground) 45%, transparent)",
	settingsAccent: "var(--primary)",
	settingsFooterButtonPrimaryFg: "var(--primary-foreground)",
	settingsSwitchOn: "var(--primary)",
	statusInReview: "#ca8a04",
	statusMerged: "var(--color-status-ready)",
	statusNeedsYou: "#ea580c",
	statusReady: "#16a34a",
	statusTerminatedForeground: "var(--chart-3)",
	statusUnknown: "var(--chart-4)",
	statusWorking: "#2563eb",
	successBright: "var(--chart-1)",
	termBlack: "#24292f",
	termBlue: "#3b5aa6",
	termBrightBlack: "#4c535b",
	termBrightBlue: "#31487f",
	termBrightCyan: "#316061",
	termBrightGreen: "#265231",
	termBrightMagenta: "#5f4476",
	termBrightRed: "#7e3330",
	termBrightWhite: "#24292f",
	termBrightYellow: "#6b5108",
	termCyan: "#3d7a7a",
	termGreen: "#2e6b3e",
	termMagenta: "#7b5799",
	termRed: "#a13c37",
	termSelectionDark: "rgb(77 141 255 / 0.3)",
	termSelectionInactive: "rgb(128 128 128 / 0.2)",
	termSelectionInactiveLight: "rgb(128 128 128 / 0.15)",
	termSelectionLight: "rgb(37 99 235 / 0.25)",
	termWhite: "#666d75",
	termYellow: "#87660f",
	textAgentsSheetDescription: "var(--muted-foreground)",
	textAgentsSheetLabel: "var(--foreground)",
	textAgentsSheetTitle: "var(--foreground)",
	textCommandItem: "var(--foreground)",
	textCommandMuted: "var(--muted-foreground)",
	textCommandPlaceholder: "var(--muted-foreground)",
	textImportMuted: "var(--muted-foreground)",
	textImportSep: "var(--color-text-import-muted)",
	textImportTitle: "var(--foreground)",
	textMarkdownCode: "var(--color-brand-logo)",
	textMarkdownLink: "var(--color-brand-logo)",
	textMarkdownLinkHover: "var(--color-brand-logo-bright)",
	textSettingsInput: "var(--foreground)",
	textSettingsMuted: "var(--muted-foreground)",
	textSettingsPlaceholder: "var(--muted-foreground)",
	textSettingsRow: "var(--foreground)",
	textSettingsTitle: "var(--foreground)",
	textTerminal: "#24292f",
	textTerminalDim: "#6b7280",
	textTopbar: "var(--foreground)",
	textTopbarMuted: "var(--muted-foreground)",
	textTopbarPassive: "var(--chart-3)",
	working: "var(--color-status-working)",
	destructive: "oklch(0.577 0.245 27.325)",
	elevationLg: "0 16px 48px color-mix(in oklch, var(--foreground) 16%, transparent)",
	elevationSm: "0 1px 0 color-mix(in oklch, var(--foreground) 6%, transparent)",
	fg: "var(--color-text-primary)",
	fgMuted: "var(--color-text-muted)",
	fgPassive: "var(--color-text-passive)",
	foreground: "oklch(0.141 0.005 285.823)",
	green: "var(--color-success)",
	input: "oklch(0.92 0.004 286.32)",
	interactiveActive: "var(--color-interactive-active)",
	interactiveHover: "var(--color-interactive-hover)",
	lineHeightBodyMd: "1.55",
	lineHeightLoose: "1.7",
	lineHeightNormal: "1.5",
	lineHeightRelaxed: "1.6",
	lineHeightRow: "1.25rem",
	lineHeightSnug: "1.42",
	muted: "oklch(0.967 0.001 286.375)",
	mutedForeground: "oklch(0.552 0.016 285.938)",
	orange: "var(--color-working)",
	popover: "oklch(1 0 0)",
	popoverForeground: "oklch(0.141 0.005 285.823)",
	primary: "oklch(0.21 0.006 285.885)",
	primaryForeground: "oklch(0.985 0 0)",
	red: "var(--color-danger)",
	ring: "oklch(0.705 0.015 286.067)",
	ringWidthFocus: "3px",
	secondary: "oklch(0.967 0.001 286.375)",
	secondaryForeground: "oklch(0.21 0.006 285.885)",
	shadowCommandPalette: "var(--elevation-xl)",
	shadowImportModal: "0 0 0 1px var(--border), var(--elevation-md)",
	shadowPopover: "var(--elevation-xl)",
	shadowSettingsDialog: "var(--elevation-xl)",
	shadowSettingsQr: "var(--elevation-md)",
	sidebar: "oklch(1 0 0)",
	sidebarAccent: "oklch(0.967 0.001 286.375)",
	sidebarAccentForeground: "oklch(0.21 0.006 285.885)",
	sidebarForeground: "oklch(0.141 0.005 285.823)",
	sidebarPrimary: "oklch(0.21 0.006 285.885)",
	sidebarPrimaryForeground: "oklch(0.985 0 0)",
	sidebarRing: "oklch(0.705 0.015 286.067)",
	surface: "var(--color-bg-secondary)",
	termBg: "var(--color-bg-terminal)",
	windowOverlayBg: "#fcfcfc",
	windowOverlaySymbol: "#3f444c",
});
